DECRIPTION: results page
rokija/quiz-game pull request #10
Opened 2019-02-19 10:54 UTC by TatjanaRu

COMMENTS: results list

2019-02-19 15:39 UTC, janisknets approved these changes

2019-02-19 15:39 UTC, janisknets commented on src/components/Results/ResultItem/ResultItem.js
> +                        <img className="ResultItem__img" src={questionImg} alt="question" />
Image should be passsed as props

2019-02-20 07:18 UTC, rokija commented on src/components/Results/ListofResults/ListofResults.js
> +// import Pagination from 'pagination-component';
remove commented out code

2019-02-20 07:19 UTC, rokija commented on src/components/Results/ListofResults/ListofResults.js
> +            activePage: 1
remove this state if it is not used anywhere

2019-02-20 07:20 UTC, rokija commented on src/components/Results/ListofResults/ListofResults.js
> +        this.setState({ activePage: pageNumber });
remove this method if it is not used

2019-02-20 07:20 UTC, rokija commented on src/components/Results/ListofResults/ListofResults.js
> +                <h1 className="ListofResults__h1">My results</h1>
betterNaming would be "ListOfResults__title"

2019-02-20 07:20 UTC, rokija commented on src/components/Results/ListofResults/ListofResults.js
> +export class ListofResults extends Component {
rename to ListOfResults

2019-02-20 07:20 UTC, rokija commented on src/components/Results/ListofResults/ListofResults.js
> +                    // {onclick = "GotoListofQuestions(quizId)"}
remove commented out code

2019-02-20 07:21 UTC, rokija commented on src/components/Results/ListofmyQuizResults/ListofmyQuizResults.css
> +    border-radius: 10px;
border-radius twice

2019-02-20 07:21 UTC, rokija commented on src/components/Results/ListofmyQuizResults/ListofmyQuizResults.js
> +// const ListofmyQuizzes = ['my First quiz', 'my Second quiz', 'my Third quiz'];
remove commented out code

2019-02-20 07:23 UTC, rokija commented on src/components/Results/ListofmyQuizResults/ListofmyQuizResults.js
> +        usersNumber: 3
what is usersNumber?

2019-02-20 07:24 UTC, rokija commented on src/components/Results/ListofmyQuizResults/ListofmyQuizResults.js
> +export class ListofmyQuizResults extends Component {
rename to ListOfMyQuizResults

2019-02-20 07:24 UTC, rokija commented on src/components/Results/ListofmyQuizResults/ListofmyQuizResults.js
> +                <h1 className="ListofmyQuizResults_h1">My quizzes results</h1>
"ListOfMyQuizResults__title"

2019-02-20 07:26 UTC, rokija commented on src/components/Results/QuestionItem/QuestionItem.js
> +        const { question, type, answers, correct, userAnswers, number } = this.props;
please rename correct to correctAnswers (I suppose its an array with correct answers?)

2019-02-20 07:26 UTC, rokija commented on src/components/Results/QuestionItem/QuestionItem.js
> +        const { question, type, answers, correct, userAnswers, number } = this.props;
also what is number?

2019-02-20 07:27 UTC, rokija commented on src/components/Results/QuestionItem/QuestionItem.js
> +                        <h3 className="QuestionItem__h2">{number}.{question}</h3>
"QuestionItem__title"

2019-02-20 07:50 UTC, janisknets requested changes

2019-02-20 07:50 UTC, janisknets commented on src/components/Results/QuestionItem/QuestionItem.js
> +                                    let index = 10
this should be null or undefined instead of arbitrary 10

2019-02-20 07:50 UTC, janisknets commented on src/components/Results/QuestionItem/QuestionItem.js
> +                                        case 0: return <div><input type={type} /><label>{answer}</label></div>
inputs should have different names

2019-02-20 07:59 UTC, TatjanaRu commented on src/components/Results/QuestionItem/QuestionItem.js
> +        const { question, type, answers, correct, userAnswers, number } = this.props;
Number is the number of question. Applied for question sequential numbering in the list.

2019-02-20 08:00 UTC, TatjanaRu commented on src/components/Results/ListofmyQuizResults/ListofmyQuizResults.js
> +        usersNumber: 3
It is a count of users who completed/fulfilled current quiz :)

2019-02-20 08:01 UTC, TatjanaRu commented on src/components/Results/QuestionItem/QuestionItem.js
> +                                    let index = 10
ok

2019-02-20 08:12 UTC, TatjanaRu commented on src/components/Results/QuestionItem/QuestionItem.js
> +                                        case 0: return <div><input type={type} /><label>{answer}</label></div>
I will add property disabled

2019-02-20 08:28 UTC, TatjanaRu commented on src/components/Results/ListofmyQuizResults/ListofmyQuizResults.js
> +        usersNumber: 3
I will rename it into usersCount

2019-02-20 12:42 UTC, janisknets approved these changes

2019-02-20 13:40 UTC, rokija commented on Git_credentials_remove.txt
> +https://stackoverflow.com/questions/37182847/how-to-disable-git-credential-manager-for-windows
why is this here?

2019-02-20 14:07 UTC, rokija commented
![screenshot 2019-02-20 at 16 06 46](https://user-images.githubusercontent.com/25583616/53097202-90284400-3529-11e9-8008-6a687e6af4b4.png)

2019-02-22 09:36 UTC, rokija approved these changes

2019-02-22 09:36 UTC, merged