Rl user card
rokija/quiz-game pull request #11
Opened 2019-02-19 13:45 UTC by lluneva

2019-02-19 13:45 UTC, lluneva commented
With static data

2019-02-19 14:03 UTC, janisknets approved these changes

2019-02-19 14:03 UTC, rokija commented on src/App.js
>        <React.Fragment>
why is React.Fragment used here?

2019-02-19 14:03 UTC, rokija commented on src/App.js
> +
remove empty line

2019-02-19 14:04 UTC, rokija commented on src/components/Usercard/Usercard.css
> +  text-align: left;
why both align-items and text-align?

2019-02-19 14:04 UTC, rokija commented on src/components/Usercard/Usercard.css
> +}
add new line

2019-02-19 14:05 UTC, rokija commented on src/components/Usercard/Usercard.css
> +}
add new line

2019-02-19 14:05 UTC, rokija commented on src/components/Usercard/Usercard.css
> +  margin-bottom: 0;
remove this

2019-02-19 14:05 UTC, rokija commented on src/components/Usercard/Usercard.css
> +}
new line

2019-02-19 14:05 UTC, rokija commented on src/components/Usercard/Usercard.css
> +}
new line

2019-02-19 14:05 UTC, rokija commented on src/components/Usercard/Usercard.css
> +.UserCard__editBtn {
rename to UserCard__edit-button

2019-02-19 14:06 UTC, rokija commented on src/components/Usercard/Usercard.js
> +      <React.Fragment>
why is React.Fragment used here?

2019-02-19 14:06 UTC, rokija commented on src/components/Usercard/Usercard.js
> +          <div className="">
remove this div if its not needed

2019-02-19 14:08 UTC, rokija commented on src/components/Usercard/Usercard.js
> +                onClick={goToUserId}
what is this function doing? is it not editUser?

2019-02-19 14:08 UTC, rokija commented on src/components/Userlist/Userlist.js
> +class Userlist extends Component {
rename to UserList

2019-02-19 14:09 UTC, rokija commented on src/components/Usercard/Usercard.js
> +                onClick={goToUserId}
ah I got it, it goes to a separate page where the user is displayed?

2019-02-19 14:09 UTC, rokija commented on src/components/Userlist/Userlist.js
> +        {/* {this.props.users && this.props.users.map((user, index) */}
remove commented out code

2019-02-19 14:18 UTC, rokija requested changes
please add human readable title and description to this pull request

2019-02-19 15:17 UTC, rokija commented
![screenshot 2019-02-19 at 17 16 31](https://user-images.githubusercontent.com/25583616/53025782-3dd41e00-346a-11e9-9059-b94529dca24d.png)

2019-02-20 07:34 UTC, rokija commented
![screenshot 2019-02-20 at 09 33 58](https://user-images.githubusercontent.com/25583616/53074149-b1ba0900-34f2-11e9-9227-bc8990d5ce8f.png)

if I click on the edit button

2019-02-20 09:48 UTC, rokija approved these changes

2019-02-20 10:29 UTC, merged