Rl login container
rokija/quiz-game pull request #20
Opened 2019-02-20 15:22 UTC by Kurkos

REFERENCE: Login & Login Container;
DESCRIPTION: Added functionality to login buttons and created LoginContainer(-Redux);

2019-02-20 15:28 UTC, rokija commented on src/components/Login/Login.js
> +export default withRouter(Login)
veeery nice:)

2019-02-20 15:29 UTC, rokija approved these changes

2019-02-20 15:39 UTC, janisknets requested changes

2019-02-20 15:39 UTC, janisknets commented on src/components/Login/Login.js
> +export default withRouter(Login)
With Router is not required since you can use <Link> for the navigation check previous comment

2019-02-20 15:39 UTC, janisknets commented on src/components/Login/Login.js
> +              <Button onClick={() => { this.props.history.push("/register") }} color="dark">
Use <Link> instead of this.props.push

2019-02-21 06:58 UTC, janisknets requested changes

2019-02-21 06:58 UTC, janisknets commented on src/components/Login/Login.js
> +import { NavLink } from 'react-router-dom';
use < Link > in stead of < NavLink >

2019-02-21 09:46 UTC, janisknets approved these changes

2019-02-21 12:43 UTC, merged