Gi kl/layout
rokija/quiz-game pull request #9
Opened 2019-02-19 10:50 UTC by gennadiyI

Layout Created

2019-02-19 12:02 UTC, gennadiyI commented
Wrong pull request branch (master denied)

2019-02-19 13:31 UTC, rokija commented on src/App.js
> +// import Layout from "./components/Layout/Layout"
remove commented out lines

2019-02-19 13:31 UTC, janisknets requested changes

2019-02-19 13:31 UTC, janisknets commented on src/components/Main/Main.js
> +
unneeded newlines

2019-02-19 13:31 UTC, janisknets commented on src/App.js
> +// import Registration from "./components/Registration/Registration"
don't keep unused commented lines

2019-02-19 13:32 UTC, rokija commented on src/App.js
> +          <div className="appSite">
please use naming according to BEM
http://getbem.com/naming/

in this case, main className should be "App",
content should be "App__content", etc..

2019-02-19 13:33 UTC, rokija commented on src/App.js
> +                  <React.Fragment>
why us React.Fragment needed here?

2019-02-19 13:34 UTC, rokija commented on src/App.js
> +                  <div className="main">
fix className naming

2019-02-19 13:35 UTC, rokija commented on src/components/Footer/Footer.js
> +    <footer>
remove <footer>, div below is enough

2019-02-19 13:35 UTC, rokija commented on src/components/Footer/Footer.js
> +
remove empty line

2019-02-19 13:35 UTC, rokija commented on src/components/Footer/Footer.js
> +      <div className="footerComponent">
rename to Footer (BEM)

2019-02-19 13:36 UTC, rokija commented on src/components/Main/Main.css
> +
remove empty lines

2019-02-19 13:36 UTC, rokija commented on src/components/Main/Main.css
> +
remove empty line

2019-02-19 13:37 UTC, rokija commented on src/components/Main/Main.css
> +/* .blockBackground {
remove commented out code

2019-02-19 13:37 UTC, rokija commented on src/components/Main/Main.js
> +// import Registration from "../Registration/Registration"
remove commented out code

2019-02-19 13:37 UTC, rokija commented on src/components/Main/Main.js
> +import   "./Main.css"
remove  empty spaces

2019-02-19 13:37 UTC, rokija commented on src/components/Main/Main.js
> +
remove empty lines

2019-02-19 13:37 UTC, rokija commented on src/components/Main/Main.js
> +        <div className="divMain">
className should be "Main"

2019-02-19 13:38 UTC, rokija commented on src/components/Main/Main.js
> +
empty lines...

2019-02-19 13:40 UTC, rokija requested changes
please add human readable titles to pull requests (instead of Gi kl/layout)

2019-02-20 09:18 UTC, janisknets approved these changes

2019-02-20 09:21 UTC, rokija approved these changes

2019-02-20 09:22 UTC, merged